<?php

return [
    'tables' => [
        'family'  => 'members',
        'areacity' => 'area_city',
    ],
    'surname' => [
        'BARHAZAR' => 'BARHAZAR',
        'BATLIWALA' => 'BATLIWALA',
        'BHADIM' => 'BHADIM',
        'BHAGAT' => 'BHAGAT',
        'BHUTTA' => 'BHUTTA',
        'BULA' => 'BULA',
        'CHIKINWALA' => 'CHIKINWALA',
        'CHIMAN' => 'CHIMAN',
        'GANDAWALA' => 'GANDAWALA',
        'GHADIYALI' => 'GHADIYALI',
        'GHODAWALA' => 'GHODAWALA',
        'HAFEJJI' => 'HAFEJJI',
        'JIGAR' => 'JIGAR',
        'KAPADIYA' => 'KAPADIYA',
        'KOLSAWALA' => 'KOLSAWALA',
        'KOTHI' => 'KOTHI',
        'LATIWALA' => 'LATIWALA',
        'MASTAR' => 'MASTAR',
        'MULLA' => 'MULLA',
        'MUNSHI' => 'MUNSHI',
        'NOORSTORE' => 'NOORSTORE',
        'REKAD' => 'REKAD',
        'SELIYA' => 'SELIYA',
        'SHETH' => 'SHETH',
        'SHETHWALA' => 'SHETHWALA',
        'SURTI' => 'SURTI',
        'WANKANERI' => 'WANKANERI',
        'ZABUK' => 'ZABUK',
    ],
    'gender' => [
        'M' => 'પુરુષ',
        'F' => 'સ્ત્રી',
    ],
    'relation_field' => [
        'Father' => 'Father / પિતા',
        'Mother' => 'Mother / માતા',
        'Wife' => 'Wife / વહુ',
        'Son' => 'Son / પુત્ર',
        'Daughter' => 'Daughter / પુત્રી',
        'Daughter in law' => 'Daughter in law / પુત્ર ની વહુ',
        'Grand Son' => 'Grand Son / પૌત્ર',
        'Grand Daughter' => 'Grand Daughter / પૌત્રી',
        'Brother' => 'Brother / ભાઈ',
        'Sister' => 'Sister / બહેન',
        'Sister in law' => 'Sister in law / ભાભી',
        'Uncle' => 'Uncle / કાકા',
        'Aunty' => 'Aunty / કાકી',
        'Nephew' => 'Nephew / ભત્રીજો',
        'Niece' => 'Niece / ભત્રીજી',
        'Grand father' => 'Grand father / દાદા',
        'Grand mother' => 'Grand mother / દાદી',
        'Great GrandSon' => 'Great GrandSon / પ્રપૌત્ર',
        'Great GrandDaughter' => 'Great GrandDaughter / પ્રપૌત્રી',
        'Granddaughter-in-law' => 'Granddaughter-in-law / પૌત્ર ની વહુ',
        'Cousin' => 'Cousin / કાકા નો છોકરો - છોકરી',
        'Husband' => 'Husband / પતિ',
    ],
    'relation_label' => [
        'Self' => 'પોતે',
        'Father' => 'પિતા',
        'Mother' => 'માતા',
        'Son' => 'પુત્ર',
        'Daughter' => 'પુત્રી',
        'Grand Son' => 'પૌત્ર',
        'Grand Daughter' => 'પૌત્રી',
        'Wife' => 'વહુ',
        'Brother' => 'ભાઈ',
        'Sister' => 'બહેન',
        'Uncle' => 'કાકા',
        'Aunty' => 'કાકી',
        'Nephew' => 'ભત્રીજો',
        'Niece' => 'ભત્રીજી',
        'Grand father' => 'દાદા',
        'Grand mother' => 'દાદી',
        'Daughter in law' => 'પુત્ર ની વહુ',
        'Sister in law' => 'ભાભી',
        'Cousin' => 'કાકા નો છોકરો - છોકરી',
        'Husband' => 'પતિ',
        'Great GrandSon' => 'પ્રપૌત્ર',
        'Great GrandDaughter' => 'પ્રપૌત્રી',
        'Granddaughter-in-law' => 'પૌત્ર ની વહુ',
    ]
];