<?php

use App\Helpers\uuid;
use App\Models\Notification\Notification;
use App\Models\Settings\Setting;
use App\Models\Events\Category;
use App\Models\Events\SubCategory;
use App\Models\Events\EventGroups;
use App\Models\Events\Transaction;
use App\Models\Events\PendingAmount;
use App\Models\Family\AreaCity;
use App\Models\Family\Family;
use Carbon\Carbon as Carbon;
use App\Models\Access\User\User;

/**
 * Henerate UUID.
 *
 * @return uuid
 */
function generateUuid()
{
    return uuid::uuid4();
}

if (!function_exists('homeRoute')) {

    /**
     * Return the route to the "home" page depending on authentication/authorization status.
     *
     * @return string
     */
    function homeRoute()
    {
        if (access()->allow('view-backend')) {
            return 'admin.dashboard';
        } elseif (auth()->check()) {
            return 'frontend.user.dashboard';
        }

        return 'frontend.index';
    }
}

/*
 * Global helpers file with misc functions.
 */
if (!function_exists('app_name')) {
    /**
     * Helper to grab the application name.
     *
     * @return mixed
     */
    function app_name()
    {
        return config('app.name');
    }
}

if (!function_exists('access')) {
    /**
     * Access (lol) the Access:: facade as a simple function.
     */
    function access()
    {
        return app('access');
    }
}

if (!function_exists('history')) {
    /**
     * Access the history facade anywhere.
     */
    function history()
    {
        return app('history');
    }
}

if (!function_exists('gravatar')) {
    /**
     * Access the gravatar helper.
     */
    function gravatar()
    {
        return app('gravatar');
    }
}

if (!function_exists('includeRouteFiles')) {

    /**
     * Loops through a folder and requires all PHP files
     * Searches sub-directories as well.
     *
     * @param $folder
     */
    function includeRouteFiles($folder)
    {
        $directory = $folder;
        $handle = opendir($directory);
        $directory_list = [$directory];

        while (false !== ($filename = readdir($handle))) {
            if ($filename != '.' && $filename != '..' && is_dir($directory.$filename)) {
                array_push($directory_list, $directory.$filename.'/');
            }
        }

        foreach ($directory_list as $directory) {
            foreach (glob($directory.'*.php') as $filename) {
                require $filename;
            }
        }
    }
}

if (!function_exists('getRtlCss')) {

    /**
     * The path being passed is generated by Laravel Mix manifest file
     * The webpack plugin takes the css filenames and appends rtl before the .css extension
     * So we take the original and place that in and send back the path.
     *
     * @param $path
     *
     * @return string
     */
    function getRtlCss($path)
    {
        $path = explode('/', $path);
        $filename = end($path);
        array_pop($path);
        $filename = rtrim($filename, '.css');

        return implode('/', $path).'/'.$filename.'.rtl.css';
    }
}

if (!function_exists('settings')) {
    /**
     * Access the settings helper.
     */
    function settings()
    {
        // Settings Details
        $settings = Setting::latest()->first();
        if (!empty($settings)) {
            return $settings;
        }
    }
}

if (!function_exists('createNotification')) {
    /**
     * create new notification.
     *
     * @param  $message    message you want to show in notification
     * @param  $userId     To Whom You Want To send Notification
     *
     * @return object
     */
    function createNotification($message, $userId)
    {
        $notification = new Notification();

        return $notification->insert([
            'message'    => $message,
            'user_id'    => $userId,
            'type'       => 1,
            'created_at' => Carbon::now(),
        ]);
    }
}

if (!function_exists('escapeSlashes')) {
    /**
     * Access the escapeSlashes helper.
     */
    function escapeSlashes($path)
    {
        $path = str_replace('\\', DIRECTORY_SEPARATOR, $path);
        $path = str_replace('//', DIRECTORY_SEPARATOR, $path);
        $path = trim($path, DIRECTORY_SEPARATOR);

        return $path;
    }
}

if (!function_exists('getMenuItems')) {
    /**
     * Converts items (json string) to array and return array.
     */
    function getMenuItems($type = 'backend', $id = null)
    {
        $menu = new \App\Models\Menu\Menu();
        $menu = $menu->where('type', $type);
        if (!empty($id)) {
            $menu = $menu->where('id', $id);
        }
        $menu = $menu->first();
        if (!empty($menu) && !empty($menu->items)) {
            return json_decode($menu->items);
        }

        return [];
    }
}

if (!function_exists('getRouteUrl')) {
    /**
     * Converts querystring params to array and use it as route params and returns URL.
     */
    function getRouteUrl($url, $url_type = 'route', $separator = '?')
    {
        $routeUrl = '';
        if (!empty($url)) {
            if ($url_type == 'route') {
                if (strpos($url, $separator) !== false) {
                    $urlArray = explode($separator, $url);
                    $url = $urlArray[0];
                    parse_str($urlArray[1], $params);
                    $routeUrl = route($url, $params);
                } else {
                    $routeUrl = route($url);
                }
            } else {
                $routeUrl = $url;
            }
        }

        return $routeUrl;
    }
}

if (!function_exists('renderMenuItems')) {
    /**
     * render sidebar menu items after permission check.
     */
    function renderMenuItems($items, $viewName = 'backend.includes.partials.sidebar-item')
    {
        foreach ($items as $item) {
            // if(!empty($item->url) && !Route::has($item->url)) {
            //     return;
            // }
            if (!empty($item->view_permission_id)) {
                if (access()->allow($item->view_permission_id)) {
                    echo view($viewName, compact('item'));
                }
            } else {
                echo view($viewName, compact('item'));
            }
        }
    }
}

if (!function_exists('isActiveMenuItem')) {
    /**
     * checks if current URL is of current menu/sub-menu.
     */
    function isActiveMenuItem($item, $separator = '?')
    {
        $item->clean_url = $item->url;
        if (strpos($item->url, $separator) !== false) {
            $item->clean_url = explode($separator, $item->url, -1);
        }
        if (Active::checkRoutePattern($item->clean_url)) {
            return true;
        }
        if (!empty($item->children)) {
            foreach ($item->children as $child) {
                $child->clean_url = $child->url;
                if (strpos($child->url, $separator) !== false) {
                    $child->clean_url = explode($separator, $child->url, -1);
                }
                if (Active::checkRoutePattern($child->clean_url)) {
                    return true;
                }
            }
        }

        return false;
    }
}

if (!function_exists('checkDatabaseConnection')) {

    /**
     * @return bool
     */
    function checkDatabaseConnection()
    {
        try {
            DB::connection()->reconnect();

            return true;
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getAllCityList')) {

    /**
     * @return bool
     */
    function getAllCityList()
    {
        try {
            $cityList = AreaCity::groupBy('city')->orderBy('id', 'asc')->pluck('city')->toArray();

            if (count($cityList) > 0)
                return $cityList;

            return [];
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getAllAreaList')) {

    /**
     * @return bool
     */
    function getAllAreaList($city = null)
    {
        try {
            if ($city == null) {
                $areaList = AreaCity::groupBy('area')->orderBy('id', 'asc')->pluck('area', 'area')->toArray();

                return $areaList;
            }

            $areaList = AreaCity::where('city', 'LIKE', '%'.$city.'%')->groupBy('area')->orderBy('area', 'asc')->pluck('area')->toArray();

            if (count($areaList) > 0)
                return $areaList;

            return [];
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getMainMemberFullDetails')) {

    /**
     * @return bool
     */
    function getMainMemberFullDetails($familyID = null)
    {
        try {

            if ($familyID == null) {
                return '';
            }

            $mainMemberArray = Family::where('id', $familyID)->whereNull('family_id')->groupBy('family_id')->first()->toArray();

            if (!empty($mainMemberArray))
                return $mainMemberArray;

            return null;
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getChildMembersDetails')) {

    /**
     * @return bool
     */
    function getChildMembersDetails($id = null)
    {
        try {

            if ($id == null) {
                return [];
            }

            $familyMemberDetails = Family::where('family_id', $id)->groupBy('id')->orderBy('id', 'asc')->get();

            if (!empty($familyMemberDetails))
                return $familyMemberDetails;

            return null;
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getChildMemberIDs')) {

    /**
     * @return bool
     */
    function getChildMemberIDs($id = null)
    {
        try {

            if ($id == null) {
                return [];
            }

            $familyMemberDetails = Family::where('family_id', $id)->where('is_main', 0)->groupBy('id')->orderBy('id', 'asc')->pluck('id')->toArray();

            if (!empty($familyMemberDetails))
                return $familyMemberDetails;

            return [];
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('isMainMember')) {

    /**
     * @return bool
     */
    function isMainMember($id = null)
    {
        try {
            if ($id == null) {
                return false;
            }

            $mainMemberArray = Family::where('id', $id)->whereNull('family_id')->where('is_main', 1)->first();

            return ($mainMemberArray == null ? false : true);
        } catch (Exception $ex) {
            return false;
        }
    }
}

/**
 * getStaffName : To get Staff name from Staff ID
 */
if (!function_exists('getStaffName')) {
    /**
     * @return String
     */
    function getStaffName($staffID = '')
    {
        if ($staffID > 0 && is_numeric($staffID)) {
            $user = User::withTrashed()->find($staffID);
            if (isset($user->first_name) && isset($user->last_name))
            return $user->first_name." ".$user->last_name;
        }

        return null;
    }
}

if (!function_exists('checkAllChildVerified')) {

    /**
     * @return bool
     */
    function checkAllChildVerified($childIDs = null)
    {
        try {
            if ($childIDs == null) {
                return false;
            }

            $mainMemberArray = Family::whereIn('id', $childIDs)->where('is_verified', 0)->get()->count();

            return ($mainMemberArray <= 0 ? true : false);
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getMainMemberID')) {

    /**
     * @return bool
     */
    function getMainMemberID($id = null)
    {
        try {
            if ($id == null) {
                return false;
            }

            if (isMainMember($id)) {
                return $id;
            }

            $mainMemberID = Family::where('id', $id)->where('is_main', 0)->value('family_id');

            return $mainMemberID;

        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getMainEventCategoriesList')) {

    /**
     * @return bool
     */
    function getMainEventCategoriesList()
    {
        try {
            $eventCategories = Category::orderBy('id', 'asc')->pluck('category_name', 'id')->toArray();

            if (count($eventCategories) > 0)
                return $eventCategories;

            return [];
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getEventGroupsList')) {

    /**
     * @return bool
     */
    function getEventGroupsList()
    {
        try {
            $eventGroups = EventGroups::orderBy('id', 'asc')->pluck('event_group_name', 'id')->toArray();

            if (count($eventGroups) > 0)
                return $eventGroups;

            return [];
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('getsubCategoryList')) {

    /**
     * @return bool
     */
    function getsubCategoryList($categoryID = null)
    {
        try {
            if ($categoryID == null) {
                return [];
            }

            $subCategoryList = SubCategory::where('category_id', $categoryID)->leftjoin('smj_event_group', 'smj_event_group.id', 'smj_event_subcategory.event_group_id')->select('smj_event_subcategory.*', 'smj_event_group.event_group_name')->get()->toArray();

            if (count($subCategoryList) > 0)
                return $subCategoryList;

            return [];
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('debitForAllCorrespondentMembers')) {

    /**
     * @return bool
     */
    function debitForAllCorrespondentMembers($eventGroupID, $debitAmount, $mainTransactionID, $note)
    {
        try {
            if ($eventGroupID > 0 && $debitAmount != '' && $mainTransactionID > 0) {
                switch ($eventGroupID) {
                    case 1: // Family wise (Dholka)
                        $memberIDs = Family::where('is_main' , 1)->whereNull('family_id')->where('city', 'LIKE', '%DHOLKA%')->where('is_relief_exception' , 0)->groupBy('id')->pluck('id')->toArray();
                        break;
                    case 2:// Family wise (All City)
                        # code...
                        break;
                    case 3:// All Members (Dholka)
                        # code...
                        break;
                    case 4:// All Members (All City)
                        $memberIDs = Family::groupBy('id')->pluck('id')->toArray();
                        break;
                    case 5:// Adult (Dholka)
                        # code...
                        break;
                    case 6:// Adult (All)
                        # code...
                        break;
                }

                if (count($memberIDs) > 0) {
                    foreach ($memberIDs as $memberID) {
                        debitTransaction($memberID, $debitAmount, $mainTransactionID, $note);
                    }

                }
            } else {
                return false;
            }

        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('debitTransaction')) {
    /**
     * Debit Amount for Members.
     *
     * @param  $message    message you want to show in notification
     * @param  $userId     To Whom You Want To send Notification
     *
     * @return object
     */
    function debitTransaction($memberID, $debitAmount, $mainTransactionID, $note = null)
    {
        $transaction = new Transaction();

        $transaction->insert([
            'member_id'        => $memberID,
            'main_trans_id'    => $mainTransactionID,
            'trans_type'       => 2,
            'note'             => $note,
            'amount'           => $debitAmount,
            'transaction_date' => Carbon::now(),
            'created_at'       => Carbon::now(),
            'created_by'       => access()->user()->id,
        ]);

        updatePendingAmount($memberID, $debitAmount, 'debited');

        return true;
    }
}

if (!function_exists('creditTransaction')) {
    /**
     * credit Amount for Members.
     *
     * @param  $message    message you want to show in notification
     * @param  $userId     To Whom You Want To send Notification
     *
     * @return object
     */
    function creditTransaction($memberID, $creditAmount, $mainTransactionID = null, $note = null, $receiptNo = null, $transactionDate = null)
    {
        $transaction = new Transaction();

        if (is_null($transactionDate)) {
            $transactionDate = Carbon::now();
        }

        $transaction->insert([
            'member_id'        => $memberID,
            'main_trans_id'    => $mainTransactionID,
            'trans_type'       => 1,
            'note'             => $note,
            'receipt_no'       => $receiptNo,
            'amount'           => $creditAmount,
            'transaction_date' => $transactionDate,
            'created_at'       => Carbon::now(),
            'created_by'       => access()->user()->id,
        ]);

        updatePendingAmount($memberID, $creditAmount, 'credited');

        return true;
    }
}

if (!function_exists('updatePendingAmount')) {
    /**
     * updatePendingAmount function
     *
     * @param [Member ID] $memberID
     * @param [Amount] $debitAmount
     * @param [Debited OR Credited] $currentAmtType
     * @return void
     */
    function updatePendingAmount($memberID, $amount, $currentAmtType)
    {
        $currentPendingAmount = PendingAmount::where('member_id', $memberID)->value('pending_amount');

        if (is_null($currentPendingAmount)) {
            if ($currentAmtType == 'debited') {
                $newPendingAmount = (floatval($amount)+floatval(0.00));
            } else if ($currentAmtType == 'credited') {
                $newPendingAmount = (floatval(0.00)-floatval($amount));
            }

            $newPendingAmount = number_format((float)$newPendingAmount, 2, '.', '');

            $transaction = new PendingAmount();

            return $transaction->insert([
                'member_id'      => $memberID,
                'pending_amount' => $newPendingAmount,
            ]);
        } else {
            if ($currentAmtType == 'debited') {
                $newPendingAmount = (floatval($amount)+floatval($currentPendingAmount));
            } else if ($currentAmtType == 'credited') {
                $newPendingAmount = (floatval($currentPendingAmount)-floatval($amount));
            }

            $newPendingAmount = number_format((float)$newPendingAmount, 2, '.', '');

            PendingAmount::where('member_id', $memberID)->update(array('pending_amount' => $newPendingAmount));

            return true;
        }
    }
}

if (!function_exists('getTransHistoryUsingMemberID')) {
    /**
     * credit Amount for Members.
     *
     * @param  $message    message you want to show in notification
     * @param  $userId     To Whom You Want To send Notification
     *
     * @return object
     */
    function getTransHistoryUsingMemberID($memberID)
    {
        $query = Transaction::leftjoin(config('access.users_table'), config('access.users_table').'.id', '=', config("smj.tables.transtable").'.created_by')
            ->leftjoin(config('smj.tables.maintranstable'), config('smj.tables.maintranstable').'.id', '=', config("smj.tables.transtable").'.main_trans_id')
            ->leftjoin(config('smj.tables.eventssubcategory'), config('smj.tables.eventssubcategory').'.id', '=', config("smj.tables.maintranstable").'.sub_category_id')
            ->leftjoin(config('smj.tables.eventsgroup'), config('smj.tables.eventsgroup').'.id', '=', config("smj.tables.eventssubcategory").'.event_group_id')
            ->leftjoin(config('smj.tables.family'), config('smj.tables.family').'.id', '=', config("smj.tables.transtable").'.member_id')
            ->where(config('smj.tables.transtable').'.member_id', $memberID)
            ->select([
                DB::raw('CONCAT('.config("smj.tables.family").'.firstname, " ", '.config("smj.tables.family").'.lastname, " ", '.config("smj.tables.family").'.surname) AS member_name'),
                DB::raw('CONCAT('.config("smj.tables.family").'.area, " / ", '.config("smj.tables.family").'.city) AS areacity'),
                DB::raw('CONCAT(users.first_name, " ", users.last_name) AS creatorName'),
                config('smj.tables.transtable').'.id',
                config('smj.tables.eventssubcategory').'.sub_category_name',
                config('smj.tables.eventsgroup').'.event_group_name',
                config('smj.tables.transtable').'.note',
                config('smj.tables.transtable').'.trans_type',
                config('smj.tables.transtable').'.member_id',
                config('smj.tables.transtable').'.receipt_no',
                config('smj.tables.transtable').'.amount',
                config('smj.tables.transtable').'.created_at',
                config('smj.tables.transtable').'.transaction_date',
        ]);

        return $query->get()->toArray();
    }
}

if (!function_exists('encryptMethod')) {
    function encryptMethod($string, $key=1958) {
        $result = '';
        for($i=0, $k= strlen($string); $i<$k; $i++) {
            $char = substr($string, $i, 1);
            $keychar = substr($key, ($i % strlen($key))-1, 1);
            $char = chr(ord($char)+ord($keychar));
            $result .= $char;
        }
        return base64_encode($result);
    }
}

if (!function_exists('decryptMethod')) {
    function decryptMethod($string, $key=1958) {
        $result = '';
        $string = base64_decode($string);
        for($i=0,$k=strlen($string); $i< $k ; $i++) {
            $char = substr($string, $i, 1);
            $keychar = substr($key, ($i % strlen($key))-1, 1);
            $char = chr(ord($char)-ord($keychar));
            $result.=$char;
        }
        return $result;
    }
}

if (!function_exists('transactionExist')) {
    /**
     * credit Amount for Members.
     *
     * @param  $message    message you want to show in notification
     * @param  $userId     To Whom You Want To send Notification
     *
     * @return object
     */
    function transactionExist($memberID)
    {
        $query = Transaction::where('member_id', $memberID)->select('*')->count();

        return $query;
    }
}